### ISSUE TITLE
How does it give texture?

### ISSUE THREAD

**Issue by inrh** [Th0rgal/Oraxen#16]
Looking forward to hearing from you, thank you.

![image](https://user-images.githubusercontent.com/39998280/72774365-508c3f80-3c45-11ea-8c67-46937d603a8d.png)
![image](https://user-images.githubusercontent.com/39998280/72774375-5b46d480-3c45-11ea-80f3-72de99ee5b2f.png)
![image](https://user-images.githubusercontent.com/39998280/72774394-6c8fe100-3c45-11ea-8037-42e4ecc39369.png)

**Comment by inrh** [comment]
![image](https://user-images.githubusercontent.com/39998280/72775324-e83f5d00-3c48-11ea-9a56-27afed566cb6.png)

**Comment by Th0rgal** [comment]
Hello,

In fact the "code" is an integer between 0 and 2^6 because a block has 6 faces and each one can be disabled or enabled. This function I wrote concerts a code to a list of faces enabled or disabled. In binary 000000, which is 0 in base 10 too, means every faces are disabled while 111111, which is equals to 63 in base 10, means that every faces are enabled. One of these combinations is reserved for the default minecraft block but the others ones are automatically generated when you try to create a new block.

Have a nice day,
Thomas!
